### ISSUE TITLE
Sitemap and permalink changes by admins

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#107]
1. Some pages that have filters still lose their filters when an admin changes the permalink. 

Example: Change: `https://science.ucsc.edu/academics/degrees/` to `https://science.ucsc.edu/academics/degree-programs/` and the page looks like this:

![screen-2020-01-31-094833](https://user-images.githubusercontent.com/36719/73562029-15d99280-440f-11ea-9c7b-7afda4880db4.jpg)

2. For some reason, it is not possible to create a page with a permalink `/people/`. This would be an overview page for a particular area of the site, such as [research](https://science.ucsc.edu/research/), or [academics](https://science.ucsc.edu/academics/).

**Comment by Herm71** [comment]
Both 1) & 2) do this for the same reason: Each are the name of a custom post type, thus their permalink slugs are "protected" and cannot be changed.

**Comment by Herm71** [comment]
Ok, fixed this.

**Comment by knice** [comment]
I've let Ryan know the **filter page slug** issue is resolved and the change pushed to production.
