### ISSUE TITLE
Permalinks setting is affecting *all* post types 

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#25]
News posts should be under `/news/`, but other post types should not. I assume this can be changed when defining the custom post type?

![screen-2019-09-20-155213](https://user-images.githubusercontent.com/36719/65363061-e1cba680-dbbe-11e9-8c93-e55e5ae7bc3b.jpg)

**Comment by Herm71** [comment]
Solution:
https://wordpress.stackexchange.com/questions/83516/change-permalinks-for-posts-but-not-for-custom-post-types

**Comment by Herm71** [comment]
From the codex: https://codex.wordpress.org/Function_Reference/register_post_type#Flushing_Rewrite_on_Activation

**Comment by Herm71** [comment]
Fixed. Needed to add `rewrite' => array('with_front' => false,),` to custom post type registration.
