### ISSUE TITLE
Sort faculty and researchers cards by slug

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#26]
On Faculty and researchers page, is it possible to use the page slug (person's last name) to sort the list?

**Comment by Herm71** [comment]
the page slug is actually the person's whole name, eg, "abraham-seiden".

**Comment by knice** [comment]
I've assigned a task to Ryan to change all of the page slugs to be last
name *only* or last name first in the slug. Go ahead and change the sort to
slug, and it will depend on Ryan changing all of the slugs (at least the
task will be off your plate).

>

**Comment by Herm71** [comment]
I might have a solution for this ...

**Comment by knice** [comment]
I juts noticed that Ryan actually has correctly added the slug to all of the people...last name only. Can you pull this field and use it for the sort?

![screen-2019-09-24-210649](https://user-images.githubusercontent.com/36719/65568663-8297ca00-df0f-11e9-8f6e-34532bc9115c.jpg)

**Comment by Herm71** [comment]
Slug won't work. I used a new ACF meta-field for that post type: "Last Name"
