### ISSUE TITLE
Set max-width so cards don't grow when less than 3 filtered results

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#27]
`_custom.scss`, line 75, change:

`grid-template-columns: repeat( auto-fit, minmax(360px, 1fr));`

to

`grid-template-columns: repeat( auto-fit, minmax(360px, 0fr));`

Keeps all of the grid loveliness without blowing out the images and making massive cards on small numbers of search results.

**Comment by Herm71** [comment]
This needs some adjustment. `class="three-col-grid"` needs adjustment on mobile. Change `0fr` to `1fr` on mobile widths to fix.
![Selection_027](https://user-images.githubusercontent.com/1000543/65609118-1bf0cb80-df64-11e9-8758-d57a5fea3cce.png)

![Selection_028](https://user-images.githubusercontent.com/1000543/65609150-24e19d00-df64-11e9-8e82-5581df9c51a7.png)
