### ISSUE TITLE
Statistics slider on the front page doesn't update when content is changed

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#36]
Perhaps this can be fixed by updating ACF Pro to version 5.8?
![screen-2019-09-24-152448](https://user-images.githubusercontent.com/36719/65554819-7c89f500-dedf-11e9-8b2d-399cf07f01c0.jpg)

**Comment by Herm71** [comment]
We're going to figure this out in 1.1 and pull for launch.
