### ISSUE TITLE
Font Awesome not working in places

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#37]
I don't have the specific location on the site.ere are collisions between two versions of Font Awesome being loaded on the site.

**Comment by Herm71** [comment]
Yeah, Ryan has mentioned this to me and I've seen it on the site. It has to do with that short-codes ultimate plugin that I'm kicking myself for ever installing. All "my" font-awesome fonts work fine. There's an update for the plugin, so I'm hoping that fixes it.a

**Comment by Herm71** [comment]
This appears to be fixed. Updated plugin, cleared cache, refreshed page, BINGO!

**Comment by knice** [comment]
🏆🏆🏆
