### ISSUE TITLE
Critical: Changes to ACF field options not reflected in edit page

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#45]
I went in and standardized the Font Awesome icon choices in the [custom fields for the home page](http://dev-ucsc-pbsci.pantheonsite.io/wp-admin/post.php?post=134&action=edit). Here is what I made them:

![screen-2019-09-25-171003](https://user-images.githubusercontent.com/36719/65648540-841ccd00-dfb7-11e9-826e-d829ac2a45c2.jpg)

After clearing caches in both WordPress and Pantheon dashboard, here is what I see when I go to [edit the icons](http://dev-ucsc-pbsci.pantheonsite.io/wp-admin/post.php?post=132&action=edit):

![screen-2019-09-25-170917](https://user-images.githubusercontent.com/36719/65648563-9dbe1480-dfb7-11e9-9072-80d3346c9cec.jpg)

**Comment by Herm71** [comment]
Weird.
