### ISSUE TITLE
Ability to select multiple filters on filter pages

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#57]
Filters need to work in tandem so users can filter by more than one criteria.

Client justification:
- When you filter the page to you desire and select a resource, you are taken off the page. When you want to return to the page (press back), the page results are back to default, this will become a frustrating experience for people who want to explore without having to continuously filter the page to their desire.
- We will be using this feature a lot. For example, when we provide a link to “advising resources” in an email, we need it to go to the https://science.ucsc.edu/academics/student-support/ with the “opportunities” category prefiltered to “academic advising.” there are many other instances where we need this functionality.

**Comment by Herm71** [comment]
fixed by #99
