### ISSUE TITLE
Update post type titles in admin panel

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#58]
Changes to the names of custom post types in the admin interface:

- [x] “Student Support” > to “Academic Support”
- [x] “Student Opportunities” > to “Research Opportunities”
- [x] “Institutes and Centers” > to “Groups & Facilities”
- [x] “Labs” > to “People”
- [x] “Support Science Organizations” > to “Support Funds”

**Comment by Herm71** [comment]
Done. This work needed to be done in the Core Functionality plugin, located [here](https://github.com/ucsc/pbsci-core-functionality-plugin).
