### ISSUE TITLE
Pad footer region so there is ample padding on any screen

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#64]
Padding on the container for the footer ensures the footer is padded no matter the screen size or width. Screenshot below does not have enough top padding.

![screen-2019-10-17-120846](https://user-images.githubusercontent.com/36719/67039810-fc6a4000-f0d6-11e9-83b5-5ed514e65759.jpg)

**Comment by Herm71** [comment]
I'm not seeing what I'm supposed to fix on this one. Looks ok to me.

**Comment by Herm71** [comment]
Fixed. See #96
