### ISSUE TITLE
Breadcrumb nav colors and decoration

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#68]
Blue blends in with the back ground. No need for pseudo class styles (`:hover`, `:active`, etc) on breadcrumbs.

**Comment by Herm71** [comment]
I think we still need a `:hover` pseudo class, as it's a link and for accessibility and whatnot, but none of the others.

**Comment by knice** [comment]
Agree. `:focus`, `:hover`, and `:active` should all get the underline you showed me.
