### ISSUE TITLE
Art direction of HP banner at different breakpoints 

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#69]
Since the banner is a BG image, the content in the banner region does not properly set height. We probably need to set explicit heights (`vh` units) at the various breakpoints.

![Screen Shot 2019-10-15 at 12 00 20 PM](https://user-images.githubusercontent.com/36719/67043361-bf09b080-f0de-11e9-8417-8c8c94bb6a65.png)

**Comment by Herm71** [comment]
Fixed
