### ISSUE TITLE
Normalize colors in footer CTA button with news room buttons

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#76]
They can't look _the same_ because they are in different contexts (light vs. dark background). But make sure blues match and the CTA button has a white bg color.

![screen-2019-10-18-104914](https://user-images.githubusercontent.com/36719/67116311-0783a580-f195-11e9-8a5f-ef8dc0c102fb.jpg)

**Comment by Herm71** [comment]
Fixed. See Pull Request #86
