### ISSUE TITLE
Font Awesome change icon selection change

### ISSUE THREAD

**Issue by knice** [ucsc/pbsci-wordpress-theme#77]
Make it so the user inputs a code for the icon rather than a dropdown select list. Client will want to change these and we don't want to limit the ~length of rope by which they can hang themselves~ number of choices.

I'm open to ideas of whether or not this is possible.

Make this an open text box?
![screen-2019-10-18-105403](https://user-images.githubusercontent.com/36719/67116608-9ee8f880-f195-11e9-9120-9089d7b4870c.jpg)

**Comment by Herm71** [comment]
The FontAwesome icons on the **home** page and **/academics/** appear to be working on `local` `dev` and `live` but they don't appear to be working on the nav menus on **/research/**.

**Comment by Herm71** [comment]
Ok, all fixed but wanted to explain for posterity. the **/research/** page *was* working, it was just working on the wrong pages in the nav menu. I'll explain, but the first field needs to be input properly. That said, I standardized all the font icons to be consistent for all drop-downs, removed "Mystery" and other superfluous icons, and re-named the Selection items to be better recognizable for applying to the pertinent nav item.
